### PR TITLE
Add build scripts

### PR DESCRIPTION
**Pull request by ebiiim**
Now we can bootstrap a development cluster with:

```sh
./hack/dev-kind-reset-cluster.sh # create a K8s cluster `kind-wao-scheduler-v2`
./hack/dev-kind-deploy.sh # build and deploy the scheduler
```

This is related to #5

### CODE REVIEW

**Review by Allez0015 — COMMENTED** [review]
wsl環境でスクリプトが実行できず下記エラーが出たのですが、これって以前出たやつでしょうか？
bit@LAPTOP-HOIAOVU6:/mnt/c/Users/direc/wao-scheduler-v2$ ./hack/dev-kind-reset-cluster.sh
/usr/bin/env: ‘bash\r’: No such file or directory

**Comment by ebiiim** [comment]
> `/usr/bin/env: ‘bash\r’: No such file or directory`

`\r` とあるので改行コードっぽいです。(もし試してなかったら)一度WSLでgit cloneからやってみてください。

**Comment by Allez0015** [comment]
スクリプト自体は動きましたが、kubectlがSegmentation faultで動かないです。
kindは動いているのですが・・。バイナリは/bin/kubectl-v1.25.0にダウンロードできています。
(一応chmod +xは試しましたが無理でした)

bit@LAPTOP-HOIAOVU6:/mnt/c/Users/direc/wao-scheduler-v2$ ./hack/dev-kind-reset-cluster.sh
= version info =
kind v0.17.0 go1.19.5 linux/amd64
hack/1-bin.sh: line 14:   943 Segmentation fault      "$KUBECTL" version --client
================

Failed to start docker.service: Unit docker.service not found.
Failed to start docker.service: Unit docker.service not found.
fs.inotify.max_user_watches = 524288
fs.inotify.max_user_instances = 512
Deleting cluster "wao-scheduler-v2" ...
Creating cluster "wao-scheduler-v2" ...
 ✓ Ensuring node image (kindest/node:v1.25.3) 🖼
 ✓ Preparing nodes 📦 📦 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
 ✓ Joining worker nodes 🚜
Set kubectl context to "kind-wao-scheduler-v2"
You can now use your cluster with:

kubectl cluster-info --context kind-wao-scheduler-v2

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
hack/2-lib.sh: line 15:  3494 Segmentation fault      "$KUBECTL" apply -f "$CERT_MANAGER_YAML"

**Comment by ebiiim** [comment]
kubectlのバイナリが正常にダウンロードできていない可能性があります。

```sh
./bin/kubectl-v1.25.0/kubectl version
```

↑これがsegfaultなら再ダウンロードしたほうがいいと思うので

```sh
rm -rf ./bin
./hack/dev-kind-reset-cluster.sh
```

**Comment by ebiiim** [comment]
```
$ ls -lh ./bin/kubectl-v1.25.0/kubectl
-rwxr-xr-x 1 me me 43M Jan 13 13:34 ./bin/kubectl-v1.25.0/kubectl
```
```
$ md5sum ./bin/kubectl-v1.25.0/kubectl
2a1ad6f2d844f4a888ffccd1d2b518ef  ./bin/kubectl-v1.25.0/kubectl
```

**Comment by Allez0015** [comment]
ありがとうございます、再ダウンロードでいけました。
deployの方は、私の環境ではscheduler pod再起動時に立ち上がったり立ち上がらなかったりしますが、
数回試せば正常に立ち上がるので、Approveしておきます。

bit@LAPTOP-HOIAOVU6:/mnt/c/Users/direc/wao-scheduler-v2$ ./hack/dev-kind-deploy.sh
= version info =
kind v0.17.0 go1.19.5 linux/amd64
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
================

/usr/bin/docker
docker build -f ./Dockerfile -t localhost/wao-scheduler-v2:v0.0.1-dev .
[+] Building 6.7s (12/12) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                        0.1s
......
 => => writing image sha256:25bf2dc18203423a520bb6b32291e84b974991e07cdcec01db8633203a2afc9a                                                                                                0.3s
 => => naming to localhost/wao-scheduler-v2:v0.0.1-dev                                                                                                                                      0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Image: "" with ID "sha256:25bf2dc18203423a520bb6b32291e84b974991e07cdcec01db8633203a2afc9a" not yet present on node "wao-scheduler-v2-worker2", loading...
Image: "" with ID "sha256:25bf2dc18203423a520bb6b32291e84b974991e07cdcec01db8633203a2afc9a" not yet present on node "wao-scheduler-v2-worker", loading...
Image: "" with ID "sha256:25bf2dc18203423a520bb6b32291e84b974991e07cdcec01db8633203a2afc9a" not yet present on node "wao-scheduler-v2-control-plane", loading...
pod/kube-scheduler-wao-scheduler-v2-control-plane image updated
pod "kube-scheduler-wao-scheduler-v2-control-plane" deleted
pod/kube-scheduler-wao-scheduler-v2-control-plane condition met

Completed!

check logs:
    kubectl logs kube-scheduler-wao-scheduler-v2-control-plane -f -nkube-system
run a Deployment:
    kubectl delete -f config/samples/dep.yaml ; kubectl apply -f config/samples/dep.yaml && sleep 2 && kubectl get pod

**Review by Allez0015 — APPROVED** [review]
スクリプトが正常に動くことを確認

**Review by Allez0015 — APPROVED** [review]
内容を確認

**Review by Allez0015 — APPROVED** [review]

**Comment by ebiiim** [comment]
ご確認ありがとうございます。

> deployの方は、私の環境ではscheduler pod再起動時に立ち上がったり立ち上がらなかったりしますが、

うーん、タイムアウトもう少し長いほうがよかったですかね？条件等わかったらまた教えてください

**Pull request merged**
